package com.bmarchand.pokemon_composite.service.domain;

public enum PokemonCapacities {
    ACID_ARMOR,
    AGILITY,
    AURORA_BEAM,
    BITE,
    CONFUSE_RAY,
    DOUBLE_EDGE,
    DOUBLE_TEAM,
    EMBER,
    FIRE_BLAST,
    FIRE_PUNCH,
    FIRE_SPIN,
    FLAMETHROWER,
    GROWL,
    HAZE,
    LEER,
    MIST,
    QUICK_ATTACK,
    RAGE,
    REST,
    SCARY_FACE,
    SCRATCH,
    SAND_ATTACK,
    SLASH,
    SMOKESCREEN,
    SWIFT,
    TACKLE,
    TAIL_WHIP,
    THUNDER,
    THUNDERBOLT,
    THUNDER_SHOCK,
    THUNDER_WAVE,
    WATER_GUN,
    WING_ATTACK
}
